[package]
name = "thin"
version = "1.0.0"
authors = ["cad97 <cad97@cad97.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
